name: CI | Build Binaries

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

env:
  WATCHTOWER_DIR: ./cmd/watchtower

jobs:
  build-watchtower-binary:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            label: linux-amd64
          - os: macos-latest
            label: darwin-arm64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1"

      - name: Build
        working-directory: ${{ env.WATCHTOWER_DIR }}
        run: go build -o watchtower_${{ matrix.label }} -ldflags "-X main.VERSION=${{ inputs.version }}" .

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: watchtower_bin
          path: ${{ env.WATCHTOWER_DIR }}/watchtower_${{ matrix.label }}
          retention-days: 1

  build-watchtower-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} #token

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: WATCHTOWER_VERISON=${{ inputs.version }}
          tags: witnesschain/watchtower:dev
