
name: Built Test & Publish - Client

on:
  release:
    types: [created]


jobs:
  build:
    env:
      client-directory: ./src/client 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      working-directory: ${{env.client-directory}}
      run: go build -v ./...

    - name: Test
      working-directory: ${{env.client-directory}}
      run: go test -v ./...


    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: Upload release binary
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./src/client/watchtower
        asset_name: watchtower
        asset_content_type: application/octet-stream

