name: Dev Release

on:
  workflow_dispatch: 
    inputs:
      watchtower_version:
        type: string
        default: v1.0-internal
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Checkout
        uses: actions/checkout@v3
      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} #token

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./src/client/
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: WATCHTOWER_VERISON=${{inputs.watchtower_version}}
          tags: witnesschain/watchtower:dev