name: CI - Smart contracts testing suite
on:
  workflow_call:
  workflow_dispatch:

env:
  RPC_URL: http://localhost:8545
  PRIVATE_KEY: '${{ secrets.TESTING_PRIVATE_KEY }}'
  AGGREGATOR: '${{ secrets.TESTING_PUBLIC_KEY }}'
  CHAIN_ID: 5
  RPC_URL_L2: http://localhost:8545
  L2_CHAIN_ID: 5

jobs:
  testbench:
    name: Setup testbench for smartcontract testing
    runs-on: ubuntu-latest
    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Anvil Fork
        run: |
          anvil --fork-url https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161 &
    
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: contract deployment 
        run: |
          cd src/smart_contracts
          make deploy-watchtower-avs-smart_contracts
          make deploy-watchtower-alert-manager-smart_contracts
          make deploy-watchtower-avs-smart_contracts-l2

      - name: registration
        run: |
          cd src/smart_contracts
          make register-operators-with-eigenlayer


      - name: Run Forge tests
        run: |
          cd src/smart_contracts
          forge test --rpc-url=$RPC_URL -vvv
      
      - name: Run Coverage
        run: |
          cd src/smart_contracts
          forge coverage --via-ir -optimize
      
