
name: Smart Contract - Analysis

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: true
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Setting up python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10' 
      - name: Setup dependencies
        run: pip3 install slither-analyzer

      - name: Running analysis
        run: |
          cd src/smart_contracts
          slither .
          
